image: node:10-alpine

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - .yarn/

stages:
  - install
  - test
  - build
  - publish

install:
  stage: install
  script:
    - yarn --pure-lockfile --cache-folder .yarn

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - yarn test

publish:
  stage: publish
  only:
    - /^\d{1,3}\.\d{1,3}\.\d{1,3}.*/
  script:
    - npx lerna publish from-package
