image: node:10-alpine

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - packages/*/node_modules
  - .yarn/

stages:
  - install
  - build
  - test
  - publish

install:
  stage: install
  script:
    - yarn --pure-lockfile --cache-folder .yarn

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - packages/*/build

test:
  stage: test
  script:
    - yarn test

publish:
  image: node:10
  stage: publish
  only:
    - tags
  script:
    - npx lerna publish from-package -y
