image: node:10-alpine

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - .yarn/

stages:
  - install
  - test
  - publish

install:
  stage: install
  script:
    - yarn --pure-lockfile --cache-folder .yarn

test:
  stage: test
  script:
    - yarn test

publish:
  stage: publish
  only:
    - master
    - tags
    - /^\d{1,3}\.\d{1,3}\.\d{1,3}.*/
  script:
    - echo "publish"
