git:
  depth: 3
  
os:
  - linux

env:
  - COVERALLS_PARALLEL=true

notifications:
  webhooks:
    - https://coveralls.io/webhook

language: node_js
node_js:
  # - "6"
  - "8"
  - "10"
  - "node"

cache: yarn
before_script:
  - yarn build
script:
  - yarn test:ci
