os: linux

git:
  depth: 3

env:
  global:
    - COVERALLS_PARALLEL=true

notifications:
  webhooks:
    - https://coveralls.io/webhook

language: node_js
node_js: "10"

cache:
  yarn: true
  directories:
    - ~/.cache/emeralt

jobs:
  include:
    - stage: build
      script:
        - yarn build
      after_script:
        - tar -cvzf ~/.cache/emeralt/build.tar.gz packages/*/build

    - stage: test
      services:
        - redis-server
        - mongodb
      before_script:
        - tar -xzvf ~/.cache/emeralt/build.tar.gz
      script:
        - yarn test:coverage --ignore @emeralt/database-cloud-firestore --ignore @emeralt/storage-gcs
