os: linux

git:
  depth: 3

env:
  global:
    - COVERALLS_PARALLEL=true

notifications:
  webhooks:
    - https://coveralls.io/webhook

language: node_js
node_js: "10"

cache:
  yarn: true
  directories:
    - ~/.cache/emeralt

jobs:
  include:
    - stage: build
      script:
        - yarn build
        - tar -cvzf ~/.cache/emeralt/build.tar.gz packages/*/build

    - stage: test
      services:
        - redis-server
        - mongodb
      before_script:
        - tar -xzvf ~/.cache/emeralt/build.tar.gz
      script:
        - yarn test:coverage --ignore @emeralt/database-cloud-firestore --ignore @emeralt/database-cloud-datastore --ignore @emeralt/storage-gcs
        - yarn nyc report --reporter=text-lcov | yarn coveralls

    - stage: test-publish
      before_script:
        - tar -xzvf ~/.cache/emeralt/build.tar.gz
        - emreg login -e $EMREG_EMAIL -p $EMREG_PASS
        - emreg create -c @emeralt
      script:
        - lerna publish from-git -y
      after_script:
        - ID=$(emreg list); emreg delete $ID

    - stage: publish
      if: tag IS present
      before_script:
        - tar -xzvf ~/.cache/emeralt/build.tar.gz
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      script:
        - lerna publish from-git -y
