os: linux

git:
  depth: 3

env:
  global:
    - COVERALLS_PARALLEL=true

notifications:
  webhooks:
    - https://coveralls.io/webhook

language: node_js

cache:
  yarn: true
  directories:
    - ~/.cache/emeralt

test_stage: &test_stage
  stage: test
  env:
    - CACHE_NAME=GLOBAL
  services:
    - redis-server
    - mongodb
  script:
    - ls -lh ~/.cache
    - ls -lh ~/.cache/emeralt
    - tar -xzvf ~/.cache/emeralt/build.tar.gz
    - yarn test:coverage --ignore @emeralt/database-cloud-firestore --ignore @emeralt/storage-gcs

jobs:
  include:
    - stage: build
      node_js: "10"
      script:
        - yarn build
        - tar -cvzf ~/.cache/emeralt/build.tar.gz packages/*/build

    - <<: *test_stage
      node_js: "8"
    - <<: *test_stage
      node_js: "10"

