git:
  depth: 3
  
os:
  - linux

env:
  global:
    COVERALLS_PARALLEL=true
    
notifications:
  webhooks:
    - https://coveralls.io/webhook

services:
  - redis-server
  
language: node_js
node_js:
  # - "6"
  - "8"
  - "10"
  - "node"

cache: yarn

before_script:
  - yarn build
script:
  - yarn test:coverage --ignore @emeralt/database-cloud-firestore --ignore @emeralt/storage-gcs
  - yarn nyc report --reporter=text-lcov | yarn coveralls
