git:
  depth: 3
  
os:
  - linux

env:
  global:
    COVERALLS_PARALLEL=true

language: node_js
node_js:
  # - "6"
  - "8"
  - "10"
  - "node"

cache: yarn
before_script:
  - yarn build
script:
  - yarn test:coverage
  
after_success: nyc report --reporter=text-lcov | coveralls
