os: linux

git:
  depth: 3

notifications:
  webhooks:
    - https://coveralls.io/webhook

language: node_js
node_js: "10"

cache:
  yarn: true
  directories:
    - ~/.cache/emeralt

jobs:
  include:
    - stage: build
      script:
        - yarn build
        - tar -cvzf ~/.cache/emeralt/build.tar.gz packages/*/build

    - stage: test
      services:
        - redis-server
        - mongodb
      env:
        global: COVERALLS_PARALLEL=true
      script:
        - ls -lh ~/.cache
        - ls -lh ~/.cache/emeralt
        - tar -xzvf ~/.cache/emeralt/build.tar.gz
        - yarn test:coverage --ignore @emeralt/database-cloud-firestore --ignore @emeralt/storage-gcs
