git:
  depth: 3
  
os:
  - linux

env:
  global:
    COVERALLS_PARALLEL=true
    
notifications:
  webhooks:
    - https://coveralls.io/webhook

services:
  - redis-server
  - mongodb

language: node_js

cache:
  yarn: true
  directories:
    - ~/.emeralt-build/build.tar.gz

jobs:
  include:

    - stage: build
      node_js: "10"
      script:
        - yarn build
      after_script:
        - rm -rf ~/.emeralt-build/build.tar.gz
        - tar -cvzf ~/.emeralt-build/build.tar.gz packages/*/build
        - ls -lh ~/.emeralt-build

    - stage: test
      node_js:
        # - "6"
        - "8"
        - "10"
        - "node"
      before_script:
        - tar -xzvf ~/.emeralt-build/build.tar.gz
        - ls packages/emeralt-server
        - rm -rf ~/.emeralt-build/build.tar.gz
      script:
        - yarn test:coverage --ignore @emeralt/database-cloud-firestore --ignore @emeralt/storage-gcs



# before_script:
#   - yarn build
# script:
#   - yarn test:coverage --ignore @emeralt/database-cloud-firestore --ignore @emeralt/storage-gcs
#   - yarn nyc report --reporter=text-lcov | yarn coveralls


    # - stage: test
    #   script:

    # - stage: phase1
    #   install:
    #   - mv ~/mycache ~/mycache-discard
    #   - mkdir ~/mycache
    #   - echo "$TRAVIS_BUILD_ID"
    #   - echo "$TRAVIS_BUILD_ID" > ~/mycache/travis_build_id
    #   - echo "build stuff" > ~/mycache/artifact.bin
    #   script:
    #   - true
    # - stage: phase2
    #   install:
    #   - if test "$TRAVIS_BUILD_ID" != `cat ~/mycache/travis_build_id`; then travis_terminate 1; fi
    #   - rm -f ~/mycache/travis_build_id
    #   - echo "Do something with ~/mycache/artifact.bin, e.g. publish it to gh-pages"
    #   - mv ~/mycache ~/mycache-discard
    #   - mkdir ~/mycache # clear the cache
    #   script:
    #   - true
