git:
  depth: 3
  
os:
  - linux

env:
  global:
    COVERALLS_PARALLEL=true
    
notifications:
  webhooks:
    - https://coveralls.io/webhook

language: node_js
node_js:
  # - "6"
  - "8"
  - "10"
  - "node"

cache: yarn

before_script:
  - yarn build
script:
  - yarn test:coverage
  - yarn nyc report --reporter=text-lcov | yarn coveralls

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: script
  script: "lerna publish -y from-package"
  skip_cleanup: true
  on:
    tags: true
